name: Sucuri Geo Block Scheduler

on:
  schedule:
    # Runs at 3:30 PM UTC every day (adjust cron as needed)
    - cron: "30 15 * * *"
    # Runs at 3:45 PM UTC every day (unblock)
    - cron: "45 15 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  sucuri:
    runs-on: ubuntu-latest
    steps:
      - name: Block US (3:30)
        if: github.event.schedule == '08 14 * * *'
        run: |
          curl -X POST https://waf.sucuri.net/api?v2 \
          -d "k=${{ secrets.SUCURI_API_KEY }}" \
          -d "s=${{ secrets.SUCURI_API_SECRET }}" \
          -d "a=update_setting" \
          -d "block_from_viewing[]=US" \
          -d "block_from_posting[]=US" \
          -d "update_geo_blocking=1"

      - name: Unblock US (3:45)
        if: github.event.schedule == '45 15 * * *'
        run: |
          curl -X POST https://waf.sucuri.net/api?v2 \
          -d "k=${{ secrets.SUCURI_API_KEY }}" \
          -d "s=${{ secrets.SUCURI_API_SECRET }}" \
          -d "a=update_setting" \
          -d "update_geo_blocking=1"
